name: Integration

on:
  workflow_dispatch:
    inputs:
      version_to_publish:
        description: "Version to be release"
        required: false

jobs:
  TestMainline:
    name: Test Mainline
    uses: ./.github/workflows/reuse_python_build.yml
    with:
      branch: mainline
    secrets: inherit

  IntegrationTests:
    needs: TestMainline
    name: Integration Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: mainline
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_RELEASE_INTEG_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: deadline-cloud-worker-agent-IntegTest
          hide-cloudwatch-logs: true
          env-vars-for-codebuild: |
            WORKER_AGENT_WHL_PATH
        env:
          WORKER_AGENT_WHL_PATH: dist/`hatch project metadata name | sed 's/-/_/g'`-`hatch version`-py3-none-any.whl