name: Mainline Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'mainline'

jobs:
  WindowsIntegrationTests:
    name: Windows Integration Tests
    runs-on: windows-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Hatch
      run: |
        pip install --upgrade hatch

    - name: Run Windows Integration Tests
      run: hatch run integ-windows
      
  MainlineIntegrationTest:
    name: Integration Test
    permissions:
      id-token: write
      contents: read
    uses: aws-deadline/.github/.github/workflows/reusable_integration_test.yml@mainline
    secrets: inherit
    with:
      repository: ${{ github.event.repository.name }}
      branch: mainline
      environment: mainline