name: Mainline E2E Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'mainline'

  

jobs:
  IntegrationTests:
    name: Integration Tests
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Hatch
      run: |
        pip install --upgrade hatch 'virtualenv<21; python_version < "3.10"'

    - name: Run Integration Tests
      run: hatch run integ-test
      
  MainlineLinuxE2ETest:
    name: Linux E2E Test
    permissions:
      id-token: write
      contents: read
    uses: aws-deadline/.github/.github/workflows/reusable_e2e_test.yml@mainline
    secrets: inherit
    with:
      repository: ${{ github.event.repository.name }}
      environment: mainline
      os: linux
    concurrency:
      group: linuxe2e

  MainlineWindowsE2ETest:
    name: Windows E2E Test
    permissions:
      id-token: write
      contents: read
    uses: aws-deadline/.github/.github/workflows/reusable_e2e_test.yml@mainline
    secrets: inherit
    with:
      repository: ${{ github.event.repository.name }}
      environment: mainline
      os: windows
    concurrency:
      group: windowse2e
