name: Mainline Integration Test

on:
  workflow_dispatch:
  push:
    branches:
      - 'mainline'

jobs:
  WindowsIntegrationTests:
    name: Windows Integration Tests
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    env:
        PYTHON: ${{ matrix.python-version }}
        CODEARTIFACT_REGION: "us-west-2"
        CODEARTIFACT_DOMAIN: ${{ secrets.CODEARTIFACT_DOMAIN }}
        CODEARTIFACT_ACCOUNT_ID: ${{ secrets.CODEARTIFACT_ACCOUNT_ID }}
        CODEARTIFACT_REPOSITORY: ${{ secrets.CODEARTIFACT_REPOSITORY }}
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_CODEARTIFACT_ROLE }}
        aws-region: us-west-2
        mask-aws-account-id: true
    
    - name: Install Hatch
      run: |
        $CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_ACCOUNT_ID }} --query authorizationToken --output text --region us-west-2)
        echo "::add-mask::$CODEARTIFACT_AUTH_TOKEN"
        echo CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN >> $env:GITHUB_ENV
        pip install --upgrade hatch

    - name: Run Windows Integration Tests
      run: hatch run integ-windows
      
  MainlineIntegrationTest:
    name: Integration Test
    runs-on: ubuntu-latest
    environment: mainline
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: mainline
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_MAINLINE_INTEG_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: deadline-cloud-worker-agent-dev-IntegTest
          hide-cloudwatch-logs: true
          env-vars-for-codebuild: |
            TEST_TYPE
        env:
          TEST_TYPE: WHEEL