name: Release Integration Canary

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  WindowsIntegrationTests:
    name: Windows Integration Tests
    runs-on: windows-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Hatch
      run: |
        pip install --upgrade hatch

    - name: Run Windows Integration Tests
      run: hatch run integ-windows
      
  ReleaseIntegrationCanary:
    name: Release Canary
    permissions:
      id-token: write
      contents: read
    uses: aws-deadline/.github/.github/workflows/reusable_canary.yml@mainline
    secrets: inherit
    with:
      repository: ${{ github.event.repository.name }}
      branch: release
      environment: canary