name: Release

on:
  workflow_dispatch:
    inputs:
      version_to_publish:
        description: "Version to be release"
        required: false

jobs:
  UnitTests:
    name: Unit Tests
    uses: ./.github/workflows/reuse_python_build.yml
    with:
      branch: mainline
    secrets: inherit

  IntegrationTests:
    needs: UnitTests
    name: Integration Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: mainline
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_RELEASE_INTEG_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: deadline-cloud-worker-agent-IntegTest
          hide-cloudwatch-logs: true
          env-vars-for-codebuild: |
            TEST_TYPE
        env:
          TEST_TYPE: WHEEL

  Merge:
    needs: IntegrationTests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0
          token: ${{ secrets.CI_TOKEN }}
      - name: Set Git config
        run: |
          git config --local user.email "client-software-ci@amazon.com"
          git config --local user.name "client-software-ci"
      - name: Update Release
        run: git merge --ff-only origin/mainline -v
      - name: Push new release
        if: ${{ inputs.version_to_publish}}
        run: |
          git tag -a ${{ inputs.version_to_publish }} -m "Release ${{ inputs.version_to_publish }}"
          git push origin release ${{ inputs.version_to_publish }}
      - name: Push post release
        if: ${{ !inputs.version_to_publish}}
        run: git push origin release