name: Release Integration Canary

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  WindowsIntegrationTests:
    name: Windows Integration Tests
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Hatch
      run: |
        pip install --upgrade hatch

    - name: Run Windows Integration Tests
      run: hatch run integ-windows
      
  ReleaseIntegrationCanary:
    runs-on: ubuntu-latest
    environment: canary
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_RELEASE_CANARY_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: deadline-cloud-worker-agent-release-Canary
          source-version-override: release
          hide-cloudwatch-logs: true