name: Release Integration Canary

on:
  workflow_dispatch:

jobs:
  ReleaseIntegrationCanary:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_RELEASE_INTEG_ROLE }}
          aws-region: us-west-2
          mask-aws-account-id: true
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: deadline-cloud-worker-agent-IntegTest
          hide-cloudwatch-logs: true
          env-vars-for-codebuild: |
            WORKER_AGENT_WHL_PATH
        env:
          WORKER_AGENT_WHL_PATH: dist/`hatch project metadata name | sed 's/-/_/g'`-`hatch version`-py3-none-any.whl