name: Mainline Windows E2E Test

on:
  workflow_dispatch:

jobs:
  MainlineWindowsE2ETest:
    name: Windows E2E Test
    permissions:
      id-token: write
      contents: read
    uses: aws-deadline/.github/.github/workflows/reusable_e2e_test.yml@mainline
    secrets: inherit
    with:
      repository: ${{ github.event.repository.name }}
      branch: mainline
      environment: mainline
      os: windows