name: Windows Integration Tests

on:
  workflow_dispatch:

jobs:
  WindowsIntegrationTests:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Hatch
      run: |
        pip install --upgrade hatch

    - name: Run Windows Integration Tests
      run: hatch run integ-windows
